# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Back-End Workflow

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Install Html2text
      run: sudo apt-get install html2text
    - name: Build Test
      working-directory: ./back
      run: mvn clean install
    - name: Display Test
      working-directory: ./back
      run: html2text target/site/jacoco/index.html

  Analysis:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        working-directory: ./back
        run: mvn clean compile
      - name: Analyzing with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONARCUBE_KEY }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          projectBaseDir: back
