# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Back-End Workflow CI/CD

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI_CD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Install Html2text
      run: sudo apt-get install html2text
    - name: Build Test
      working-directory: ./back
      run: mvn clean install
    - name: Display Test
      working-directory: ./back
      run: html2text target/site/jacoco/index.html
    - name: Build
      working-directory: ./back
      run: mvn clean compile
    - name: Analyzing with SonarCloud
      uses: SonarSource/sonarcloud-github-action@v2.2.0
      env:
        SONAR_TOKEN: ${{ secrets.SONARCUBE_KEY }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
      with:
        projectBaseDir: back
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image for Back-End
      working-directory: ./back
      run: docker build -t lennyisaac14/bobapp-back .
    - name: Deploy Docker image to Docker Hub
      working-directory: ./back
      run: docker push lennyisaac14/bobapp-back:latest
    - name: Get docker image
      run: docker save lennyisaac14/bobapp-back > back-image.tar
    - name: Save docker image
      uses: actions/upload-artifact@v4
      with:
        name: image-output
        path: |
          back-image.tar
    - name: Save coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-output
        path: |
          back/target/site/jacoco/
