name: Docker Image Back CD

on:
  push:
    branches: [ "main" ]
    paths:
      - back/**
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image for Back-End
      working-directory: ./back
      run: docker build -t lennyisaac14/bobapp-back .
    - name: Deploy Docker image to Docker Hub
      working-directory: ./back
      run: docker push lennyisaac14/bobapp-back:latest
