name: Docker Image Front CD

on:
  push:
    branches: [ "main" ]
    paths:
      - front/**
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for Front-End
      working-directory: ./front
      run: docker build -t bobapp-front .
    - name: Deploy Docker image to Docker Hub
      working-directory: ./front
      run: docker push lennyisaac14/bobapp-front:latest
