# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Front-End Workflow

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'front/package-lock.json'
    - name: Clean Insall
      working-directory: ./front
      run: npm ci
    - name: Build
      working-directory: ./front
      run: npm run build --if-present
    - name: Test
      working-directory: ./front
      run: npm test
    - name: Analyzing with SonarCloud
      uses: SonarSource/sonarcloud-github-action@v2.2.0
      env:
        SONAR_TOKEN: ${{ secrets.SONARCUBE_KEY }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
      with:
        projectBaseDir: front
      
